### ISSUE TITLE
Compilation Error with HPCX

### ISSUE THREAD

**Issue by bugByteMe** [ExtremeFLOW/neko#1069]
When I execute `make`
The following error occurs:
```
mpif90  -g  -Mbackslash -c -o common/signal.o common/signal.f90
NVFORTRAN-S-0038-Symbol, bge, has not been explicitly declared (common/signal.f90: 91)
```
when compiling with the following configure:
```
./configure --prefix=INSTALL_DIR --with-cuda=/home/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/cuda 
CUDA_CFLAGS=-O3  CUDA_ARCH=-arch=sm_80 
NVCC=/home/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/compilers/bin/nvcc
```

The compilers are from nvidia hpcx tool kit, which activate by
```
module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc-hpcx/23.5
```

mpif90 version is 
```
nvfortran 23.5-0 64-bit target on x86-64 Linux -tp icelake-server 
NVIDIA Compilers and Tools
Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
```

Could you please help me to figure out what's wrong with signal.f90?
I will fully appreciate it.

**Comment by njansson** [comment]
NVIDIA Fortran doesn't support enough of f2008 to compile 'signal.f90' out of the box. However, unless you need the signal handler, there's a patch under patches which can be applied to make Neko compile with nvfortran,

'git apply patches/nvhpc_bge.patch'

**Comment by bugByteMe** [comment]
> NVIDIA Fortran doesn't support enough of f2008 to compile 'signal.f90' out of the box. However, unless you need the signal handler, there's a patch under patches which can be applied to make Neko compile with nvfortran,
> 
> git apply patches/nvhpc_bge.patch

This works. Fully thanks for your reply.

**Comment by timofeymukha** [comment]
@njansson Do you remember if this is in the documentation?

**Comment by njansson** [comment]
> @njansson Do you remember if this is in the documentation?
No we don't, maybe we should add a section in the appendix for "Known issues for flaky compilers"

**Comment by timofeymukha** [comment]
Yes, something like that

**Comment by bugByteMe** [comment]
@njansson By the way, does neko support multi-NVIDIA GPUs?

**Comment by timofeymukha** [comment]
> @njansson By the way, does neko support multi-NVIDIA GPUs?

Do you mean running on multiple GPUs? Then the answer is yes.

**Comment by bugByteMe** [comment]
> > @njansson By the way, does neko support multi-NVIDIA GPUs?
> 
> Do you mean running on multiple GPUs? Then the answer is yes.

Yeah. Then what is the suggested compile combination? openmpi + --with-cuda, or other choices?

**Comment by timofeymukha** [comment]
Essentially yes, see here for and example
https://github.com/ExtremeFLOW/neko/discussions/540

**Comment by njansson** [comment]
> > > @njansson By the way, does neko support multi-NVIDIA GPUs?
> 
> > 
> 
> > Do you mean running on multiple GPUs? Then the answer is yes.
> 
> 
> 
> Yeah. Then what is the suggested compile combination? openmpi + --with-cuda, or other choices?

Most options should be covered here:

https://github.com/ExtremeFLOW/neko/discussions/540

Note neko assumes one device per mpi rank, and this has to be assigned from the environment, typically via environment variables

**Comment by bugByteMe** [comment]
> Essentially yes, see here for an example #540
> 
> (Note Niclas' comment about --enable-device-mpi, that gives a significant perfomance boost)

Thanks. I'll refer to that. 

Sorry for another question about profiling. When I dynamically load IPM when running the executable created by `makeneko`, nothing happened. I'm also confused that, if I want to link the profiler statically, when should I let it in. When compiling neko? Or when compiling my code using `makeneko`?

**Comment by BeiNing-Z** [comment]
sorry to bother you ,but  I use the same way as you, when I run the tgv_Re1600.case, I meet the problem:

 -------------Case-------------
 Reading case file tgv_Re1600.case
FIO-F-217/namelist read/unit=10/attempt to read past end of file.
 File name = 'tgv_Re1600.case',    formatted, sequential access   record = 21
 In source file case.f90, at line number 119
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

could you help me ,thanks very much
