### ISSUE TITLE
Wrong output by probes if `csv_file` used in the user file

### ISSUE THREAD

**Issue by vbaconnet** [ExtremeFLOW/neko#1079]
Issue was noticed by running the `lid` example with probes. In this example, we compute and output the kinetic energy and enstrophy by manipulating `file_t` and `vector_t` objects.

# Steps to reproduce

Add the following lines to `lid.case` in the `simulation_components` section:

```json
    {
      "type": "probes",
      "points_file": "probes.csv",
      "compute_control": "tsteps",
      "compute_value": 1,
      "fields": ["u","v","w","p"],
      "output_file": "fileprobe.csv"
    }
```

And create `probes.csv` containing the following coordinates:

```
0.0,0.5,0.5
0.55,0.5,0.5
1.0,0.5,0.5
```

Also modify the `end_time` parameter to:
```json
 "end_time": 5e-3
```

To only run for a few timesteps.

# Expected behavior

We expect to see an output from the probes like:

```
0.0000000000000000,0.50000000000000000,0.50000000000000000
0.55000000000000004,0.50000000000000000,0.50000000000000000
1.0000000000000000,0.50000000000000000,0.50000000000000000
0.10000000000000000E-2,0.0000000000000000,0.0000000000000000,0.0000000000000000,-0.24573430219930988E-12
0.10000000000000000E-2,0.59728200608949555E-15,0.37459328365942781E-15,0.10858132173933643E-29,-0.33679609678643655E-12
0.10000000000000000E-2,0.0000000000000000,0.0000000000000000,0.0000000000000000,-0.40550112745446832E-12
```

Here we see that the 3 first lines are the coordinates of our probes, and we then have rows of 5 values: `time, u, v, w, p`.

# Observed behavior

Instead, we observe an output probes files like:

```
0.0000000000000000,0.50000000000000000,0.50000000000000000
0.55000000000000004,0.50000000000000000,0.50000000000000000
1.0000000000000000,0.50000000000000000,0.50000000000000000
0.10000000000000000E-2,0.0000000000000000,0.0000000000000000
```

We now see that the rows following the coordinates only contain 3 values: `t` and what is suspected to be the values set in the user file of `Ekin` and `enst`:
```.f90
    type(file_t) output_file    ! output file
    type(vector_t) :: vec_out ! will store our output data
    
    output_file = file_init("output.csv")
    call output_file%set_header("t,Ekin,enst")
    call vec_out%init(2) ! Initialize our vector with 2 elements (Ekin, enst)
    
    ! ... compute e1 and e2 ...
    vec_out%x = (/e1, e2/)
    call output_file%write(vec_out, t)
```

It seems that the call to `output_file%write` is somehow conflicting with the output workflow in `probes`.

**Comment by vbaconnet** [comment]
So, after some investigations it seems to come from `csv_file_write`, and the pointers that are initialized to `null()` [(here)](https://github.com/ExtremeFLOW/neko/blob/557708062b27602b900523aa3abd0db3492e6baf/src/io/csv_file.f90#L71-L72) as follows:
```.f90
    type(vector_t), pointer :: vec => null()
    type(matrix_t), pointer :: mat => null()
```

The association of `vec` or `mat` is later done depending on the input type in `csv_file_write` ([here](https://github.com/ExtremeFLOW/neko/blob/557708062b27602b900523aa3abd0db3492e6baf/src/io/csv_file.f90#L74-94)) :

```.f90
    select type(data)
    type is (vector_t)
       vec => data

    type is (matrix_t)
       mat => data

    class default
       call neko_error("Invalid data. Expected vector_t or &
       &matrix_t")
    end select
```

Then, we check if either `vec` or `mat` is associated. If `vec` (resp. `mat`) is associated, we call the corresponding `csv_file_write_vector` (resp. `csv_file_write_matrix`) function ([here](https://github.com/ExtremeFLOW/neko/blob/557708062b27602b900523aa3abd0db3492e6baf/src/io/csv_file.f90#L99-104)).

```.f90
       if (associated(vec)) then
          call csv_file_write_vector(this, vec, t)
       else if (associated(mat)) then
          call csv_file_write_matrix(this, mat, t)
       end if
```

Naturally, one would expect that when entering the subroutine, both `vec` and `mat` would be `null` pointers. However, it seems that after calling `csv_file_write` in the user file with an input type `vector_t`, any subsequent call to `csv_file_write` with an input type `matrix_t` from the probes will enter the subroutine with `vec` being associated to the `vector_t` object initially used in the user file. Even though we call the subroutine from a different `file_t` object.

So, it seems that declaring pointers as:

```.f90
    type(vector_t), pointer :: vec => null()
    type(matrix_t), pointer :: mat => null()
```

Does not properly set the pointers to `null()`. I have found a workaround, to manually set `vec` and `mat` to `null`:

```.f90
    type(vector_t), pointer :: vec => null()
    type(matrix_t), pointer :: mat => null()

    if (associated(vec)) vec => null()
    if (associated(mat)) mat => null()
```

**Comment by timofeymukha** [comment]
So, is it the same object, which takes care of both the probes and the csv opened in the usr?

**Comment by timofeymukha** [comment]
Perhaps, one can just do
`nullify(vec)`, thus avoiding the if? I guess it is never meant to be associated at that stage, or?

**Comment by vbaconnet** [comment]
> So, is it the same object, which takes care of both the probes output and the csv opened in the usr?

No, I am still very confused as to why this is happening. Each I/O operation in probes is done with a different file object, same goes for the file object in the user file.

> Perhaps, one can just do `nullify(vec)`, thus avoiding the if? I guess it is never meant to be associated at that stage, or?

What is the difference between `nullify(vec)` and `vec => null()`? And yes you are right, the `if` statements are not necessary since both `vec` and `mat` are not meant to be associated at that stage.

**Comment by njansson** [comment]
> > So, is it the same object, which takes care of both the probes output and the csv opened in the usr?
> 
> No, I am still very confused as to why this is happening. Each I/O operation in probes is done with a different file object, same goes for the file object in the user file.
> 
> > Perhaps, one can just do `nullify(vec)`, thus avoiding the if? I guess it is never meant to be associated at that stage, or?
> 
> What is the difference between `nullify(vec)` and `vec => null()`? And yes you are right, the `if` statements are not necessary since both `vec` and `mat` are not meant to be associated at that stage.

Not 100% sure what the standard says about pointer assignment (=>) when declaring a variable in a procedure, but give what has been observed, it seems to behave like for any other variable with an assignment, resulting in an implicit save statement on that variable (causing it to be static, and retain the value for each invocation)

This does not apply to type members, where one should use `=> nullify()` to set sane initial values.

**Comment by vbaconnet** [comment]
I see! I changed this part of the code to:
```.f90
    type(vector_t), pointer :: vec
    type(matrix_t), pointer :: mat
    nullify(vec)
    nullify(mat)
```

And it seems to work fine.
