### ISSUE TITLE
Primary job terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted.

### ISSUE THREAD

**Issue by BeiNing-Z** [ExtremeFLOW/neko#1087]
sorry to bother you ,but I use the same way as you, when I run the tgv_Re1600.case with **mpirun  --allow-run-as-root -np 1 ./neko tgv_Re1600.case**, I meet the problem:

-------------Case-------------
Reading case file tgv_Re1600.case
FIO-F-217/namelist read/unit=10/attempt to read past end of file.
File name = 'tgv_Re1600.case', formatted, sequential access record = 21
In source file case.f90, at line number 119
Primary job terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
--------------------------

could you help me ,thanks very much

**Comment by timofeymukha** [comment]
Hi. Where is that case, and what version of neko are you using?

**Comment by BeiNing-Z** [comment]
the case is in tgv_Re1600 ,and the neko  version is 0.6.1

**Comment by BeiNing-Z** [comment]
It run on NVIDIA GPUs

**Comment by BeiNing-Z** [comment]
https://github.com/ExtremeFLOW/neko/issues/1069#issue-2034905216, I use his way to compile

**Comment by timofeymukha** [comment]
Would you be willing to migrate to the latest release? There are many changes, particularly to the case file format, which is now JSON.

**Comment by njansson** [comment]
> sorry to bother you ,but I use the same way as you, when I run the tgv_Re1600.case with **mpirun --allow-run-as-root -np 1 ./neko tgv_Re1600.case**, I meet the problem:
> 
> ## -------------Case-------------
> Reading case file tgv_Re1600.case
> FIO-F-217/namelist read/unit=10/attempt to read past end of file.
> File name = 'tgv_Re1600.case', formatted, sequential access record = 21
> In source file case.f90, at line number 119
> Primary job terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> could you help me ,thanks very much

Adding an empty line after the last `/` in the case file should fix the problems with PGI/nvfortran

**Comment by BeiNing-Z** [comment]
but it stiil have the warning:
 *** ERROR: Memory allocation on device failed ***
Warning: ieee_underflow is signaling
Warning: ieee_inexact is signaling
ERROR STOP

**Comment by BeiNing-Z** [comment]
but it stiil have the warning:
 *** ERROR: Memory allocation on device failed ***
Warning: ieee_underflow is signaling
Warning: ieee_inexact is signaling
ERROR STOP

**Comment by njansson** [comment]
That would indicate that your device can't fit the entire problem size. Either use a device with more memory, or run across multiple devices, by using more mpi ranks, and map each rank to an own devices via a wrapper script. See for example
https://github.com/ExtremeFLOW/flettner_rotor/blob/main/run.sh
