### ISSUE TITLE
ERROR: Memory allocation on device failed 

### ISSUE THREAD

**Issue by BeiNing-Z** [ExtremeFLOW/neko#1088]
when I mpirun tgv_RE1600 on NVIDIA GPU , it stiil have the warning, The neko version is 0.6.1 . 
*** ERROR: Memory allocation on device failed ***
Warning: ieee_underflow is signaling
Warning: ieee_inexact is signaling
ERROR STOP

**Comment by njansson** [comment]
That would indicate that your device can't fit the entire problem size. Either use a device with more memory, or run across multiple devices, by using more mpi ranks, and map each rank to an own devices via a wrapper script. See for example
https://github.com/ExtremeFLOW/flettner_rotor/blob/main/run.sh
