### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by BeiNing-Z** [ExtremeFLOW/neko#1092]
When I execute make
The following error occurs:
NVFORTRAN-S-0038-Symbol, bge, has not been explicitly declared (common/signal.f90: 91)
  0 inform,   0 warnings,   1 severes, 0 fatal for signal_usr
when compiling with the following configure:
./configure --prefix=INSTALL_DIR --with-cuda=/opt/nvidia/hpc_sdk/Linux_x86_64/23.11/cuda/ CUDA_CFLAGS=-O3  CUDA_ARCH=-arch=sm_70  NVCC=/opt/nvidia/hpc_sdk/Linux_x86_64/23.11/compilers/bin/nvcc --enable-device-mpi
mpif90 version is
nvfortran 23.11-0 64-bit target on x86-64 Linux -tp cascadelake
NVIDIA Compilers and Tools
Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

and I have already used the 
git apply patches/nvhpc_bge.patch

Could you please help me to figure out what's wrong with signal.f90?
I will fully appreciate it.

**Comment by njansson** [comment]
duplicate #1093
