### ISSUE TITLE
Abstract BDF type

### ISSUE THREAD

**Issue by MartinKarp** [ExtremeFLOW/neko#114]
In order to be able to use different BDF schemes a new BDF type is necessary with subroutines such as 'bdf%apply'

**Comment by timofeymukha** [comment]
I'm wondering if we actually need this. Nek has this whole linear system solution going down to be able to get coefficients for an arbitrary-order BDF, but is anything but 2nd and 3rd actually used? If not, we could just hardcode that and be done.

**Comment by njansson** [comment]
I agree, if we don't need more than 2nd and 3rd order (in the foreseeable future), we should probably just hardcode it, and fix the array sizes
