### ISSUE TITLE
Example issue: Lid

### ISSUE THREAD

**Issue by timfelle** [ExtremeFLOW/neko#1164]
The lid example does not complete with the case file supplied in the example.

-------Job Information--------  
Start time: 06:52 / 2024-03-04
Running on: 1 MPI rank
CPU type  : Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
Bcknd type: Accelerator (CUDA)
Dev. name : NVIDIA A100-PCIE-40GB
Real type : double precision

<details>
<summary>Last time step</summary>

```
----------------------------------------------------------------
   t =   0.4693600E+02                                  [  93.87% ]
   ----------------------------------------------------------------
   Time-step:  46937
    CFL:  0.3994580+165 dt:  0.1000000E-02
  
       ------------Fluid-------------  
       Projection Pressure
       Proj. vec.:   Orig. residual:
                 5          Infinity
 *** WARNING: New vector not linearly indepependent! ***
 *** WARNING: New vector not linearly indepependent! ***
 *** WARNING: New vector not linearly indepependent! ***
 *** WARNING: New vector not linearly indepependent! ***
       Pressure
       Iterations:   Start residual:     Final residual:
                 1          Infinity       0.0000000E+00
       X-Velocity
       Iterations:   Start residual:     Final residual:
               201               NaN                 NaN
       Y-Velocity
       Iterations:   Start residual:     Final residual:
               201               NaN                 NaN
       Z-Velocity
       Iterations:   Start residual:     Final residual:
               201               NaN                 NaN
       *** ERROR: Fluid solver diverged  ***

```
</details>

**Comment by Shiyu-Sandy-Du** [comment]
Seems the problem is with the projection. Did you successfully run the case without any projections? (Currently the projection is spurious for both CPU and GPU, and I am currently working on it)

**Comment by timfelle** [comment]
I only tested whether the examples we supply will run without any modification, which they should, so i guess we should just turn off the projections for this case?

**Comment by Shiyu-Sandy-Du** [comment]
It's just my suspicion that the problem is from projections. I have no idea whether this case works or not without projections. Could you please test it once? If it works, then we should just turn off the projections and turn on it again once the projection is fixed.
