### ISSUE TITLE
Update the statistics documentation

### ISSUE THREAD

**Issue by timfelle** [ExtremeFLOW/neko#1299]
As evident from the discussion [https://github.com/ExtremeFLOW/neko/discussions/1130](https://github.com/ExtremeFLOW/neko/discussions/1130), currently the statistics are poorly documented. This needs to be adjusted, hopefully we can make it before 0.8.

**Comment by timofeymukha** [comment]
As a first step, we need to document the fields that are generated and put into the s1... fields in the .flds.

**Comment by pschlatt1** [comment]
I guess we need to talk more about the statistics in general. I know we did that already a few times, but the strategy needs to be clear. It is a major effort, but crucially important I would say. My recommendation is in fact to start with a prototype of just first and second order statistics, to explore how it can be done.

**Comment by timfelle** [comment]
> As a first step, we need to document the fields that are generated and put into the s1... fields in the .flds.

My thoughts exactly. And reading the code was not enough for me to get a grip on it and start a draft PR.

In general it would be great if the fld files could contain the names of the fields, as the `field_t` already contain the name.

**Comment by timofeymukha** [comment]
Yeah, hdf5 will hopefully solver the latter in the future

**Comment by MartinKarp** [comment]
Created an initial draft.
