### ISSUE TITLE
Current develop (as of 1st of august 2024) fails on GPUs

### ISSUE THREAD

**Issue by adperezm** [ExtremeFLOW/neko#1406]
Hi,

As the title says. The fluid solver diverges when executed on the GPU. This has been observed on an Nvidia RTX4080 and on AMD GPUs in Lumi.

We have tried the TS_Channel case on both GPUs. It also failed for me on a Rayleigh Bernard Convection simulation. Therefore it does not seem to be that the problem is the example.

Everything seems to work on the CPUs. 

The problem might be very recent, as reverting to a branch 2 or 3 days old, the code runs.

**Comment by Shiyu-Sandy-Du** [comment]
Could you also run a clean case such as turb_channel etc.? Could it be the something related to io? (like probes in RBC and binary file reading in TS channel)

**Comment by adperezm** [comment]
Good guess, but why would the solver diverge?

In any case, the RBC I used did not have probes. It was just scalar and source term.

I can try the channel on Monday.

**Comment by Shiyu-Sandy-Du** [comment]
Oh then I don't think it could be the io issue. In my previous TS_channel tests, similar first-step-crash happens when I read the binary file in a wrong dimension. (that's the motivation of my previous guess). But since you don't have probe in your test, so my guess is most probably wrong. : \

**Comment by njansson** [comment]
I'm working on a fix, this is due to the unified stress and none-stress fluid solver...

**Comment by adperezm** [comment]
Great! thank you!
