### ISSUE TITLE
Convergence issues if compiled with GNU Fortran 14.2.0

### ISSUE THREAD

**Issue by njansson** [ExtremeFLOW/neko#1474]
If compiled with GNU Fortran 14.2.0, the pressure will directly diverge with NaN

**Comment by gregorweiss** [comment]
Hello @njansson,

I was about to open an issue when I saw this issue. I might have a related/similar issue using GNU Fortran 10.2.0 and MPT 2.26 on Hawk nodes (`2 Socket AMD EPYC 7702 64-Core`) at HLRS. 

Running the TGV case (32768 elements + settings from `examples/tgv`) on four nodes (512 cores) results in:
```
    --------Postprocessing--------  
 ----------------------------------------------------------------
 t =   0.8500000E+00                                  [   4.25% ]
 ----------------------------------------------------------------
 Time-step:     86
  CFL:  0.4241661E+82 dt:  0.1000000E-01
  
    --------Preprocessing---------  
  
    ------------Fluid-------------  
    Projection Pressure
    Proj. vec.:   Orig. residual:
             20          Infinity
 *** WARNING: New vector not linearly indepependent! ***
    Pressure
    Iterations:   Start residual:     Final residual:
              1          Infinity       0.0000000E+00
    X-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    Y-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    Z-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    *** ERROR: Fluid solver diverged  ***
```

The problem slightly depends on the level of parallelism. When using one or two nodes (128 or 256 cores) the simulation crashes one time step later. 

Is this similar to what this issue deals with or should I open a separate issue?

I can also pass on further compilation and job details if needed.

**Comment by njansson** [comment]
> Hello @njansson,
> 
> I was about to open an issue when I saw this issue. I might have a related/similar issue using GNU Fortran 10.2.0 and MPT 2.26 on Hawk nodes (`2 Socket AMD EPYC 7702 64-Core`) at HLRS.
> 
> Running the TGV case (32768 elements + settings from `examples/tgv`) on four nodes (512 cores) results in:
> 
> ```
>     --------Postprocessing--------  
>  ----------------------------------------------------------------
>  t =   0.8500000E+00                                  [   4.25% ]
>  ----------------------------------------------------------------
>  Time-step:     86
>   CFL:  0.4241661E+82 dt:  0.1000000E-01
>   
>     --------Preprocessing---------  
>   
>     ------------Fluid-------------  
>     Projection Pressure
>     Proj. vec.:   Orig. residual:
>              20          Infinity
>  *** WARNING: New vector not linearly indepependent! ***
>     Pressure
>     Iterations:   Start residual:     Final residual:
>               1          Infinity       0.0000000E+00
>     X-Velocity
>     Iterations:   Start residual:     Final residual:
>             801               NaN                 NaN
>     Y-Velocity
>     Iterations:   Start residual:     Final residual:
>             801               NaN                 NaN
>     Z-Velocity
>     Iterations:   Start residual:     Final residual:
>             801               NaN                 NaN
>     *** ERROR: Fluid solver diverged  ***
> ```
> 
> The problem slightly depends on the level of parallelism. When using one or two nodes (128 or 256 cores) the simulation crashes one time step later.
> 
> Is this similar to what this issue deals with or should I open a separate issue?
> 
> I can also pass on further compilation and job details if needed.

Not sure, but I suspect it's a different issue than for 14.2.0.

Have you tried with a single node?

**Comment by gregorweiss** [comment]
I ran with more tool chains and job sizes, and branched it off into issue #1504.

**Comment by njansson** [comment]
This issue was due to an issue with OpenMPI v5.0.5 where `MPI_Allreduce` calls with `MPI_IN_PLACE` resulted in zero.
