### ISSUE TITLE
Automake preprocessing

### ISSUE THREAD

**Issue by timfelle** [ExtremeFLOW/neko#1499]
The current setup does not enforce preprocessing of our files with the C-Pre-Processor (-cpp for gnufortran fx.) However, we explicitly use preprocessor macros in certain parts of the code (`device_math.f90` fx.)

Should we move to runtime configuration set by `neko_config.f90`? 
Or should we enforce preprocessing?

Our current approach actually does not switch off the device interfaces at compile time.

**Comment by njansson** [comment]
Preprocessing is enabled for all files ending in `.F90`. 

The current setup will as said compile a lot of empty modules for the disabled backend, but I think that is ok compared to having harder to read heavily preprocessed files (at list in my opinion)

**Comment by timfelle** [comment]
I see, so the issue I was running into was me changing the file extension of `device_math.F90` to `device_math.f90` 😅

**Comment by timfelle** [comment]
What is the reason for not preprocessing `.f90` files, compared to `.F90`?

**Comment by njansson** [comment]
> What is the reason for not preprocessing `.f90` files, compared to `.F90`?

Following old conventions.
