### ISSUE TITLE
Residuals diverge in TGV case using 32k and 256k elements

### ISSUE THREAD

**Issue by gregorweiss** [ExtremeFLOW/neko#1504]
While the 512 element case runs smoothly, the 32k element case starts diverging at around t = 0.8 and crash after a few more time steps. (The 256k element case shows similar issue but was not fully tested as listed below.)
See also https://github.com/ExtremeFLOW/neko/issues/1474#issuecomment-2368520276

On commit 213bc8b60b

On Hawk nodes at HLRS:
2 Socket AMD EPYC 7702 64-Core

Job information:
 Various Job sizes from one socket to eight nodes.
 CPU type  : AMD EPYC 7742 64-Core Processor
 Bcknd type: CPU
 Real type : double precision

Several tested tool chains show the same behaviour:
GNU Fortran 10.2.0, 12.2.0, or 13.1.0
MPT 2.26
MKL 2023.1.0 or 19.1.3

```
 ----------------------------------------------------------------
 t =   0.8400000E+00                                  [  28.00% ]
 ----------------------------------------------------------------
 Time-step:     85
  CFL:  0.1882355E+39 dt:  0.1000000E-01
  
    --------Preprocessing---------  
  
    ------------Fluid-------------  
    Projection Pressure
    Proj. vec.:   Orig. residual:
             19     0.7499093E+73
    Pressure
    Iterations:   Start residual:     Final residual:
            800     0.7508619E+73       0.2290615E+57
    X-Velocity
    Iterations:   Start residual:     Final residual:
            801     0.3080410E+71       0.8295510E+71
    Y-Velocity
    Iterations:   Start residual:     Final residual:
            801     0.3561466E+71       0.2438613E+71
    Z-Velocity
    Iterations:   Start residual:     Final residual:
            801     0.5850903E+71       0.2361203E+66
    Fluid step time (s):     0.2455072E+02
    Total elapsed time (s):  0.8293190E+02
  
    --------Postprocessing--------  
  
    ---------Step summary---------  
    Total time for step       85 (s):   0.2455081E+02
    Total elapsed time (s):             0.8293199E+02
 ----------------------------------------------------------------
 t =   0.8500000E+00                                  [  28.33% ]
 ----------------------------------------------------------------
 Time-step:     86
  CFL:  0.2081231E+79 dt:  0.1000000E-01
  
    --------Preprocessing---------  
  
    ------------Fluid-------------  
    Projection Pressure
    Proj. vec.:   Orig. residual:
             20          Infinity
 *** WARNING: New vector not linearly indepependent! ***
    Pressure
    Iterations:   Start residual:     Final residual:
              1          Infinity       0.0000000E+00
    X-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    Y-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    Z-Velocity
    Iterations:   Start residual:     Final residual:
            801               NaN                 NaN
    *** ERROR: Fluid solver diverged  ***
```

**Comment by gregorweiss** [comment]
Well, I found my problem with the help of @muenschm. I did not adjust the time stepping for the larger meshes. Adjusting the time stepping to variable and setting a target CFL works all fine...

**Comment by lcebaman** [comment]
@muenschm @gregorweiss  could you please specify where and what needs be changed? Facing the same issue

**Comment by gregorweiss** [comment]
Check also further options that could be helpful: https://neko.cfd/docs/develop/dd/d33/case-file.html
For instance, if you with to fine-tune it, check out options like `cfl_max_update_frequency` , `max_dt_increase_factor`,  and more.

The proposed solution from @muenschm is already all you need to get it running.

**Comment by lcebaman** [comment]
thanks @muenschm . I'll give it  a go. By the way, what is the memory consumption per MPI rank as we increase the number of elements?   My jobs hang in the Gather-Scatter section until all memory per node is sucked and then follows a crash.

``` console
--------Gather-Scatter--------
   Comm         :          MPI
```

**Comment by muenschm** [comment]
hard to answer this question without any details, but however once you increase the number of elements substantially, you also have to increase the number of CPUs (or GPUs). Maybe try to keep the ratio fixed.

**Comment by MartinKarp** [comment]
> thanks @muenschm . I'll give it a go. By the way, what is the memory consumption per MPI rank as we increase the number of elements? My jobs hang in the Gather-Scatter section until all memory per node is sucked and then follows a crash.
> 
> ```
> --------Gather-Scatter--------
>    Comm         :          MPI
> ```

The memory consumption is ballpark around 1-2GB per 1000 elements or so. If one enables a lot of projections and fluid statistics it increases by quite a bit though, for TGV this is not the case though.
