### ISSUE TITLE
Merge subroutines in plan4

### ISSUE THREAD

**Issue by MartinKarp** [ExtremeFLOW/neko#158]
As we usually run with very few iterations of our Krylov solvers, optimizing the setup of the rhs in plan4 can have a large impact on the I/O cost.

**Comment by njansson** [comment]
@MartinKarp can we mark this as done, given the new solver in #388, #398, #405?

**Comment by MartinKarp** [comment]
I guess, to some extent. There is still room for optimization, but I guess this will be a gradual process rather than a standing issue.
