### ISSUE TITLE
Invalid coefficients when computed using HIP

### ISSUE THREAD

**Issue by njansson** [ExtremeFLOW/neko#504]
With the introduction of accelerated generation of coefficients (pr #500), the routine `coef_generate_dxyzdrst` generates "garbage" when offloaded to an AMD GPU via HIP.

Currently, these coefficients are computed on CPUs if the HIP backend is enabled (pr #501)

**Comment by jonvin73** [comment]
Not sure if this is related or additional,  but looks like a general failure for the cases when LX*LX*LX>1024 as you are setting it as with blocksize 1024

`const int iii = threadIdx.x;`

` if (iii < (LX * LX * LX)) {
    shw3[iii] = w3[iii];
  }`

but when you access it you have

`const int ijk = iii + n * CHUNKS;`

`G11[ijk + e * LX * LX * LX] *= shw3[ijk];`

So looks like a general failure for both HIP and CUDA when lx>=11

i.e. nchunks needs to be used for the initial setting of the shared memory as well.

**Comment by njansson** [comment]
Indeed that's a bug, thanks for spotting it.

However, there's still something strange since the results differ for lx well below 11 (~ 6-8)
