### ISSUE TITLE
tgv example dies due to initial condition

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#518]
For some reason, tgv dies on me with the following, and similar for my own channel case. Both kebnekaise and a local Spack build. Makeneko ran without issues and I have a user.mod file.
````
      --------Gather-Scatter--------
      Avg. internal:       249856
      Avg. external:            0
      Backend      :          std

      --------Gather-Scatter--------
      Avg. internal:        77824
      Avg. external:            0
      Backend      :          std
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
ERROR STOP

Error termination. Backtrace:
 *** ERROR: Dummy user defined initial condition set ***
#0  0x40876b in __utils_MOD_neko_error_msg
        at common/utils.f90:122
#1  0x4f9d38 in __flow_ic_MOD_set_flow_ic_usr
        at fluid/flow_ic.f90:91
#2  0x4d3873 in __case_MOD_case_init
        at /home/t/timofey/neko/src/case.f90:195
#3  0x5324a7 in __neko_MOD_neko_init
        at /home/t/timofey/neko/src/neko.f90:195
#4  0x402f52 in turboneko
        at /home/t/timofey/neko/src/driver.f90:6
#5  0x402f52 in main
        at /home/t/timofey/neko/src/driver.f90:3
````

**Comment by njansson** [comment]
Interesting, which compiler version and which mpi?

**Comment by timofeymukha** [comment]
GCC/11.2.0, OpenMPI/4.1.1

**Comment by MartinKarp** [comment]
I will checkout Keb quick and see what I find

**Comment by MartinKarp** [comment]
I just pulled the most recent develop, loaded GCC/11.2.0 and OpenMPI/4.1.1 as well as OpenBLAS/0.3.18 and made a fresh install.
I was able to run the tgv.case just fine on the basic CPU partition with both pnpn and plan4. Have you made any changes to the case or f90 file?

**Comment by timofeymukha** [comment]
No... it's probably something super-stupid due to the approaching friday evening. I will report later :-)

**Comment by timofeymukha** [comment]
I didn't realize a new local neko executable is generated by makeneko and was trying to run the case with the main neko, which obviously didn't work. Sorry :).
