### ISSUE TITLE
Potential off by one error on device_name

### ISSUE THREAD

**Issue by jonvin73** [ExtremeFLOW/neko#524]
For the hip device name you do (CUDA version essentially the same)

`end_pos = scan(c_name, C_NULL_CHAR)`

 `name(1:end_pos) = c_name(1:end_pos)`

This means that the C_NULL_CHAR is also copied to name, which is not correct for FORTRAN strings (which are padded with spaces as I understand it).

For some reason device name is returning null (with end_pos=1) on the local system, which results in

-------Job Information-------- 
 Start time: 19:18 / 2022-05-19
 Running on: 1 MPI rank
 Bcknd type: Accelerator (HIP)
 Dev. name : ^@
 Real type : double precision

The binary as part of the device name I think is related to the above, but not sure.

**Comment by njansson** [comment]
Indeed, off-by-one 🍺  Please file a pr.

Regarding `hipDeviceGetName`, it's "expected" to be empty. It has been labelled as a known issue by AMD in ROCm starting at v4.4 or v4.5, with a "will be fixed in future releases".

**Comment by jonvin73** [comment]
Fixed in #525
