### ISSUE TITLE
Bank conflicts for LX=8 in AX kernel (CUDA)

### ISSUE THREAD

**Issue by jonvin73** [ExtremeFLOW/neko#549]
Seems like we have some clear bank conflicts for LX=8 in the AX kernel (stepping through the slower moving dimension of a 2D array with a power of 2 for the fastest moving dimension) means the shared memory in that case is mostly from the same memory banks, which reduces the available bandwidth.

Potentially a problem for all powers of 2 for LX (2,4,8,16). I guess in reality the most important one is likely to be 8.

Given that the memory bandwidth utilization goes from 90% to 80% to 90% for lx=9,8,7 for the tgv benchmark, it is probably about a 10% effect for ax with lx=8.

The simple solution is to just create a separate lx=8 kernel where we have (lx * (lx+1)) for the shared memory sizes and update the indices for accessing them to account for the padding of the faster moving dimension. 

If there is a better way to structure it let me know, otherwise I can make a pull request for my solution. Given that the cpu versions have got different functions for various LX, I guess it not too big a deal to make a different one here. Can also keep it templated so we can use it for 2,4,8,16 as needed.

**Comment by njansson** [comment]
Sounds good, I like the idea of two templated kernels, one for power of two and another for non power of two. What do you think @MartinKarp?

**Comment by MartinKarp** [comment]
Sounds good to me

**Comment by jonvin73** [comment]
OK for the large tgv case with LX=8 was seeing a reduction from 756us to 570us

For now just turned it on for LX8 in the pull request. LX=2 for sure it is not needed as it is only 4 doubles anyway for the array. LX=4 probably also needed as it is 2 cache lines for the array.

LX=16 it should also be needed, but not tested it yet.
