### ISSUE TITLE
AMD Optimisation of AX HELM kernel

### ISSUE THREAD

**Issue by jonvin73** [ExtremeFLOW/neko#570]
Ok I pushed the potential fix for the ax helm kernel on AMD. The AMD compilers have a problem with the kernel used in CUDA version due to the large amount of registers used. Setting launch bounds seems to mostly fix this, forcing the compiler to be more efficient with register use. 

From what Niclas wrote before we possibly need to do something more complicated with it I tested with the bk5 benchmark and the larger version of the tgv benchmark provided.

For the kernel names I went with kstep for the "CUDA Style" version as it is stepping through k inside the kernel. The old version is called 1D, so went with that. Could easily change them if someone has better ideas for names.

For BK5 we see consistently better performance on both Mi100 and Mi200 as long as the number of elements is large enough. For the tgv_large case it was more complicated. For lx10 using the ksteping version was significantly better, but lx8 and lx9 was more complicated.

**Comment by njansson** [comment]
With #579 merged, can we close this? Or is there more work to be done?

**Comment by jonvin73** [comment]
Yes it can be closed
