### ISSUE TITLE
consistent naming of points, size and dofs

### ISSUE THREAD

**Issue by pschlatt1** [ExtremeFLOW/neko#626]
dof should refer to only unique degrees of freedom, not the whole list of all points on a given mesh. Therefore, the following changes are required:
in dofmap:
- make the variable n_dofs private, and replace all existing codes with a function call to u%dof%size()
- rename the (now private) variable n_dofs with ntot, where needed

Later, one should probably also reconsider the naming of "points" in the mesh class as vertices.

**Comment by njansson** [comment]
These things were fixed in #670, except the naming of "points" -> "vertex", which will be something to revisit with the new revised mesh class
