### ISSUE TITLE
User interface and naming conventions

### ISSUE THREAD

**Issue by MartinKarp** [ExtremeFLOW/neko#646]
I group these under the same issue as they all relates to the user interface
- [x] #640 
- [x] #632
- [x] #626 

When we address the changes to the user interface we should also make sure as too accommodate scalars in a suitable way.

**Comment by timofeymukha** [comment]
We discussed passing the field registry to user routines at the hackathon, so that one can init any registered field, for example.

**Comment by njansson** [comment]
> We discussed passing the field registry to user routines at the hackathon, so that one can init any registered field, for example.

But do we need to pass it? Isn't it already accessible since the user interface includes `use neko`

**Comment by timofeymukha** [comment]
Oh ok, that's right. Then I guess there is no issue.
