### ISSUE TITLE
Scalar transport

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#648]
This is to describe the state of PR #622 at the end of the hackathon. The principle result is that there is machinery for transport of 1 scalar, and also for output into files called `scalar#.fld`. Several issues remain, big and small.

- [ ] Extension to any number of scalars by extending `scalar_method` to hold an array of scalars and associated looping in other places.
- [x] As a subcase of the above that requires more thinking: output of 100s of scalars, how can that fit into the current fld file model? Should we allow to flag which scalars should be output?
- [x] Write device implementation for scalar residual computation
- [x] Write device implementation for scalar makebdf/makeabf, etc
- [x] Use factory methods and base classes instead of concrete cpu-based classes for the above in `scalar_method`
- [x] Boundary conditions for scalars
- [x] The whole machinery for user input: ICs, sources, diffusivities, cp, etc.
- [x] Logic checking that scalars are to be computed for the case at hand.
- [x] Potentially reuse space/dofs in fluid_scheme for the scalar_scheme.
Additionally started on that branch:
- [x] Refactoring makebdf/ab for better naming, e.g. ab -> ext
- [ ] currently we have scalar_method and scalar_pnpn following the convention in fluid. Does that make sense? Probably no, since pnpn referers to pressure-velocity coupling.
- [x] Add dealiasing.

**Comment by timofeymukha** [comment]
@njansson @MartinKarp the stuff here https://github.com/ExtremeFLOW/neko/tree/feature/scalars/src/scalar/bcknd will need your review

**Comment by njansson** [comment]
> @njansson @MartinKarp the stuff here https://github.com/ExtremeFLOW/neko/tree/feature/scalars/src/scalar/bcknd will need your review

Looks good! But, you will also need to modify `src/device/opencl/prgm_lib.{F90,h}` accordingly, for the scalars kernel

**Comment by njansson** [comment]
For the last item on the list, should one just merge `scalar_method` and `scalar_pnpn` into a simple `scalar` ?

**Comment by timofeymukha** [comment]
Yes, probably. It'll be a pretty bigg class then. But I guess there is really no logic in how things are split now.
