### ISSUE TITLE
Scratch registry for temporaries

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#801]
Hello! Got a bit inspired and wrote some code for managing temporaries. It is kind of similar to the field registry. Probably buggy atm, but this is to show the idea.
https://github.com/ExtremeFLOW/neko/blob/feature/scratch_registry/src/field/scratch_registry.f90

The idea is that when you need a temporary, you use the `get_field` subroutine, which will point a pointer to a managed scratch field and also give you an integer index. You can then use the field, and it is reserved for you until you relinquish it by calling `relinquish_field(index)`.

Currently, fixed it to fields with the same `dofmap`, but I guess this will be the case for all fields in the near future.

I think this could radically reduce the amount of temporaries stored as class members (you can store a private `scratch_registry` or use a global one) and also work arrays in interface definitions. The only issue I see right now is that one would have to not forget to relinquish stuff.

**Comment by njansson** [comment]
Sounds good, how about also adding a registry of generic temporary arrays `vector_t` , covering the cases when you need an array but don't have for example a dofmap

**Comment by timofeymukha** [comment]
Merged! We keep in mind the idea to create one for `vector_t` as well.
