### ISSUE TITLE
Adding a test

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#806]
I'm trying to figure out how to add a unit test. A draft of what I could figure out is written here in order to hopefully make things less painful for others.
https://github.com/ExtremeFLOW/neko/blob/feature/scratch_registry/doc/pages/testing.md

However, following this process, my test still doesn't compile due to
`*** No rule to make target 'scratch_registry_suite', needed by 'check'.  Stop.`

So I guess I would like someone to review these instructions, and help me find what is not working.

**Comment by timofeymukha** [comment]
The issue was not editing configure.ac
I updated the documentation page.
So someone should just see if it looks good now.

**Comment by njansson** [comment]
Looks good! Covering the tricky parts!

**Comment by timofeymukha** [comment]
Closing, everything is merged
