### ISSUE TITLE
Deferred constructors/destructors

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#817]
We have the following in the `fluid_scheme_t` class, and, by copy/paste, in `scalar_scheme_t`.

```
     procedure(fluid_method_init), pass(this), deferred :: init
     procedure(fluid_method_free), pass(this), deferred :: free
``` 
So, this forces the constructors of all subclasses to adhere to a particular interface, which I think is a strange thing to do. The situation where a derived class has additional attributes, which should be initialized by passing them to the constructor, is of course possible. So forcing a constructor interface seems unreasonable.

Is the idea here to just "remind" people that one should have `init` and `free` in the derived classes so that one calls the associated function in the base? I think we simply have to rely on the programmer's skill for this when it comes to these things in Fortran :-(.

**Comment by njansson** [comment]
> Also, I guess we don't use `final` for destructors due to poor compile support?

Indeed, we had some issues in the past where it was called too early (see https://github.com/ExtremeFLOW/neko/pull/523)

**Comment by njansson** [comment]
> We have the following in the `fluid_scheme_t` class, and, by copy/paste, in `scalar_scheme_t`.
> 
> ```
>      procedure(fluid_method_init), pass(this), deferred :: init
>      procedure(fluid_method_free), pass(this), deferred :: free
> ```
> 
> So, this forces the constructors of all subclasses to adhere to a particular interface, which I think is a strange thing to do. The situation where a derived class has additional attributes, which should be initialized by passing them to the constructor, is of course possible. So forcing a constructor interface seems unreasonable.
> 
> Is the idea here to just "remind" people that one should have `init` and `free` in the derived classes so that one calls the associated function in the base? I think we simply have to rely on the programmer's skill for this when it comes to these things in Fortran :-(.

My understanding of the standards is that if the `init` function has different arguments, we can't call `init` on the base class, but instead have to either define which type we're using, or have it inside a `select type` block (not nice inside `case` imo)

**Comment by timofeymukha** [comment]
OK, so to summarize the situation.
1. We want a universal `init` that can be called when initializing a derived type via an allocatable to `class` of the base type.
2. Yet, the base class has 2 different constructors with different call signatures.

I agree that 1. kind of implies that the derived types have to all have just one constructor with the same signature. What we do now is have the base constructor as a generic that points to the 2 different constructors and then deffer the actual  "common" constructor to the derived types. 

I've set for way to long in Compiler Explorer, but the best I could do is instead have a third constructor in base, which is the common one, and which is just empty in base. Then, all the derived classes just override that one. The plus here is that there is this one `init` generic that can be used for everything. But this advantage is kind of marginal to be honest. My original idea was to be able more constructors to the derived types (in case they are ever used directly), but it is not possible to point a generic in the base class to additional function implemented in the derived one :-(.

**Comment by timofeymukha** [comment]
For completeness, my experiment. Constructors are really a pain point in Fortran.
```fortran
module test_module
    ! base class with two constructors via a generic, plus a dummy common constructor
    type :: base_t
      contains
        procedure, pass(this) :: init_one => init_base_one
        procedure, pass(this) :: init_two => init_base_two

        ! this one does nothing
        procedure, pass(this) :: init_common => init_base_common
        generic :: init => init_one, init_two, init_common
    end type base_t

    ! overrides one of the contructors
    type, extends(base_t) :: deriv1_t
      contains
        procedure, pass(this) :: init_common => init_deriv_one
    end type deriv1_t

    ! overrides the other constructor
    type, extends(base_t) :: deriv2_t
      contains
        procedure, pass(this) :: init_common => init_deriv_two
    end type deriv2_t

    contains

    subroutine factory(object, selector)
        class(base_t), intent(inout), allocatable :: object
        integer :: selector

        if (selector .eq. 1) then
            write(*,*) "Building 1"
            allocate(deriv1_t::object)
        else if (selector .eq. 2) then
            write(*,*) "Building 2"
            allocate(deriv2_t::object)
        end if

    end subroutine

    subroutine init_base_one(this, a, b)
      implicit none
      class(base_t), intent(inout) :: this
      integer, intent(in) :: a, b
            write(*,*) "Calling base one"
    end subroutine

    subroutine init_base_two(this, a, b, c)
      implicit none
      class(base_t), intent(inout) :: this
      integer, intent(in) :: a, b, c
            write(*,*) "Calling base two"
    end subroutine

    subroutine init_base_common(this, a)
      implicit none
      class(base_t), intent(inout) :: this
      integer, intent(in) :: a

            write(*,*) "Calling base common"
    end subroutine

    subroutine init_deriv_one(this, a)
      implicit none
      class(deriv1_t), intent(inout) :: this
      integer, intent(in) :: a
      integer :: b
            write(*,*) "Calling deriv one"
      call this%base_t%init(a, b)
    end subroutine

    subroutine init_deriv_two(this, a)
      implicit none
      class(deriv2_t), intent(inout) :: this
      integer, intent(in) :: a
      integer :: b, c
            write(*,*) "Calling deriv two"
      call this%base_t%init(a,b,c)
    end subroutine
end module
```

**Comment by timofeymukha** [comment]
I gues we can close for now.
