### ISSUE TITLE
Support for multiple types of source terms

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#824]
* The current implementation of the source term is that of  procedure pointer, that is allocated, based on the parameter file, to either do nothing or a variant of the user-defined source, see ` subroutine fluid_scheme_set_source` in `fluid_method.f90`.
* I envision that the `source_t` type instead be the base for various sources encapsulating physics and sometimes numerics (e.g. filtering). For example, an ABL simulation would make use of filtering, a Coriolis, and a Boussinesq source term, each parametrized in the case file.
* A rough sketch would then be to have an array of polymorphic `source_t` objects in the `fluid_scheme_t`, and a method that gets access to the case file, and performs both allocation and init of the sources, and then adds them to the array. Then, we loop through the array and call `eval` on all of them.

Thoughts? I will try to create a small demo.

**Comment by njansson** [comment]
Sounds good!

**Comment by timofeymukha** [comment]
Starting to work on this now.

**Comment by njansson** [comment]
Does #962 fix this one, or only partially?

**Comment by timofeymukha** [comment]
Yes, it fixes it. The third bullet in the list here is more or less what is implemented.

**Comment by timofeymukha** [comment]
So, we should be able to directly use the constant term in e.g. the pipe or for a channel if needed. And then we can start adding stuff like Coriolis, Bousinesq, rotating reference frame, and so on. And also expand to the scalar.

**Comment by njansson** [comment]
Ok, great! 🍻

**Comment by timofeymukha** [comment]
Also: sponge/fringe, tripping. 
(just putting it down for future reference)
