### ISSUE TITLE
JSON case file layout

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#858]
Here is an attempt to produce a layout, which incorporates everything we have in the parameter file, except for old statistics stuff. It is difficult to define sometime what is general and what should be in e.g. `fluid`. I tried to make all the names as obvious as possible, without resorting to abbreviations or trying to save space. Please share your thoughts!

```json
{
  "general": {
    "mesh_file": "hemi.nmsh",
    "output_boundary": false,
    "output_partitions": false,
    "output_checkpoints": true,
    "output_at_end": true,
    "output_directory": "",
    "checkpoint_control": "simulationtime",
    "checkpoint_parameter": 10000, !we need a better name for these...
    "load_balance": false,
    "job_timelimit": "00:00:00",
    "restart_file": "",
    "end_time": 0.0,
    "timestep": 0.0
  },
  "numerics": {
    "time_order": 3,
    "polynomial_order": 7,
    "dealias": true,
    "dealiased_space_size": 0
  },
  "fluid": {
    "scheme": "pnpn",
    "rho": 1.0,
    "mu": 1.0,
    "Re": 1.0,
    "source_term": "noforce",
    "blasius": {
      "approximation": "sin",
      "freestream_velocity": [0.0, 0.0, 0.0],
      "delta": 1.0
    },
    "initial_condition": {
      "type": "blasius"
    },
    "inflow_condition": {
      "type": "default"
    },
    "outflow_condition": {
      "type": "dong",
      "velocity_scale": 1.0,
      "delta": 0.01
    },
    "boundary_types": ["w", "v"],
    "flow_rate_force": {
      "direction": 0,
      "rate": 0.0,
      "use_averaged_flow": true
    },
    "velocity_solver": {
      "type": "cg",
      "preconditioner": "jacobi",
      "projection_space_size": 0,
      "absolute_tolerance": 1e-9,
      "max_iterations": 800
    },
    "pressure_solver": {
      "type": "gmres",
      "preconditioner": "hsmg",
      "projection_space_size": 20,
      "absolute_tolerance": 1e-9,
      "max_iterations": 800
    },
    "output_control": "org",
    "output_value": 10000
  },
  "scalar": {
    "enabled": false,
    "source_term": "noforce",
    "Pr": 1.0,
    "boundary_types": ["t", "f"]
  },
  "statistics": {
    "enabled": false,
    "output_control": "simulationtime",
    "output_value": 10000,
    "start_time": 0.0,
    "sampling_interval": 10
  }
}
```

**Comment by timofeymukha** [comment]
Note that I only propose the keywords here. The values are mostly defaults taken from the parameter file code.

**Comment by njansson** [comment]
My suggestions would be to remove `general`, and add a top level called `case`, which contains everything for a given case (fluid, scalars, etc). Then we can even provide several cases in side one json blob if we for example control this from pyneko

**Comment by timofeymukha** [comment]
A new example, this is hemi
```json
{
"case": {
    "mesh_file": "hemi.nmsh",
    "output_at_end": true,
    "output_boundary": true,
    "output_checkpoints": false,
    "end_time": 2,
    "timestep": 0.001,
    "numerics": {
        "time_order": 3,
        "polynomial_order": 5,
        "dealias": true
    },
    "fluid": {
        "scheme": "pnpn",
        "rho": 1,
        "mu": 1,
        "Re": 1400,
        "source_term": {
            "type": "noforce"
        },
        "initial_condition": {
            "type": "blasius"
        },
        "inflow_condition": {
            "type": "blasius"
        },
        "blasius": {
            "approximation": "sin",
            "delta": 0.6,
            "freestream_velocity": [1.0, 0.0, 0.0]
        },
        "velocity_solver": {
            "type": "cg",
            "preconditioner": "jacobi",
            "projection_space_size": 4,
            "absolute_tolerance": 1e-7,
            "max_iterations": 800
        },
        "pressure_solver": {
            "type": "gmres",
            "preconditioner": "hsmg",
            "projection_space_size": 4,
            "absolute_tolerance": 1e-7,
            "max_iterations": 800
        },
        "output_control": "nsamples",
        "output_value": 100
    }
}
}
```

**Comment by njansson** [comment]
> A new example, this is hemi
> 
> ```json
> 
> {
> 
> "case": {
> 
>     "mesh_file": "hemi.nmsh",
> 
>     "output_at_end": true,
> 
>     "output_boundary": true,
> 
>     "output_checkpoints": false,
> 
>     "end_time": 2,
> 
>     "timestep": 0.001,
> 
>     "numerics": {
> 
>         "time_order": 3,
> 
>         "polynomial_order": 5,
> 
>         "dealias": true
> 
>     },
> 
>     "fluid": {
> 
>         "scheme": "pnpn",
> 
>         "rho": 1,
> 
>         "mu": 1,
> 
>         "Re": 1400,
> 
>         "source_term": {
> 
>             "type": "noforce"
> 
>         },
> 
>         "initial_condition": {
> 
>             "type": "blasius"
> 
>         },
> 
>         "inflow_condition": {
> 
>             "type": "blasius"
> 
>         },
> 
>         "blasius": {
> 
>             "approximation": "sin",
> 
>             "delta": 0.6,
> 
>             "freestream_velocity": [1.0, 0.0, 0.0]
> 
>         },
> 
>         "velocity_solver": {
> 
>             "type": "cg",
> 
>             "preconditioner": "jacobi",
> 
>             "projection_space_size": 4,
> 
>             "absolute_tolerance": 1e-7,
> 
>             "max_iterations": 800
> 
>         },
> 
>         "pressure_solver": {
> 
>             "type": "gmres",
> 
>             "preconditioner": "hsmg",
> 
>             "projection_space_size": 4,
> 
>             "absolute_tolerance": 1e-7,
> 
>             "max_iterations": 800
> 
>         },
> 
>         "output_control": "nsamples",
> 
>         "output_value": 100
> 
>     }
> 
> }
> 
> }
> 
> ```

Nice! Do you know how to handle bc lists in a good way (without having to specify all 20 or so possibly)?

**Comment by njansson** [comment]
> @njansson Not really, but it seems that it suffices to only add empty entries for the bcs preceding the ones you want to specify. Here is RB for example.
> 
> ```json
> {
> "case": {
>     "mesh_file": "box.nmsh",
>     "output_at_end": true,
>     "output_boundary": true,
>     "end_time": 1000,
>     "timestep": 0.01,
>     "numerics": {
>         "time_order": 3,
>         "polynomial_order": 5,
>         "dealias": true
>     },
>     "fluid": {
>         "scheme": "pnpn",
>         "rho": 1,
>         "mu": 1,
>         "Re": 1715,
>         "source_term": {
>             "type": "user_vector"
>         },
>         "initial_condition": {
>             "type": "user"
>         },
>         "velocity_solver": {
>             "type": "cg",
>             "preconditioner": "jacobi",
>             "projection_space_size": 4,
>             "absolute_tolerance": 1e-6,
>             "max_iterations": 800
>         },
>         "pressure_solver": {
>             "type": "gmres",
>             "preconditioner": "hsmg",
>             "projection_space_size": 4,
>             "absolute_tolerance": 0.000001,
>             "max_iterations": 800
>         },
>         "output_control": "simulationtime",
>         "output_value": 10,
>         "boundary_types": ["", "", "", "", "w", "w"]
>     },
>     "scalar": {
>         "enabled": true,
>         "source_term": {
>             "type": "noforce"
>         },
>         "Pr": 0.71,
>         "boundary_types": ["", "", "", "", "d=1", "d=0"]
>     }
> }
> ```
> 
> It kinda looks weird, but I think we can live with this for now. In the future, we would need to change this so that one has one json object per boundary condition and field, where one both specifies the type and the properties. As it stands, it is, for example, impossible to say what boundary the `inflow_condition` refers to in hemi. And the "mesh-embedded" bcs make things somehow even more obscure.

Agree we can probably live with this for now, but having a lot of magic empty strings in the parameter file is not ideal. Would it be too much work to go with an object per bc already now?

**Comment by MartinKarp** [comment]
I do not think one object per bc is a good idea, I do not see that scaling to many scalars and different types of boundary conditions.

**Comment by timofeymukha** [comment]
I think nothing really scales with many scalars :-). I think if you end up having 10s of unknowns, the case file is bound to become kinda giant. But why wouldn't it scale with types of boundary conditions?

**Comment by MartinKarp** [comment]
I mostly thought if you meant that we would have one parameter (bc1='d', bc2='w') for each quantity that would be a hassle

**Comment by timofeymukha** [comment]
Yeah, if we get a huge number of quantities, then yes. I am still not sure how real is the prospect of getting that, though. I realize combustion can be a case in point, but I don't actually know any details. I think we should a bit at how other codes deal with this. E.g. in OpenFOAM each new field is an extra file where you configure the ics/bcs, so 100s of unknowns would be a nightmare there, but I am pretty sure they do combustion.

**Comment by MartinKarp** [comment]
I think having one list for each is fine. Or maybe if we have that instead of we havebc_fluid = 'w','v' bc_scalar = 'd=1','d=0' we can have that label1 ='w','d=1'  for example label2=''v",'d=0', each position corresponding to one quantity

**Comment by timofeymukha** [comment]
I think we need a whiteboard for this :D. I think regarding the bcs I will at a later point summarize the status (with your help Martin) and some possible directions, and then we discuss it on the Fri meeting.

**Comment by timofeymukha** [comment]
I mean in principle nothing is impossible :-)

**Comment by pschlatt1** [comment]
I mean it seriously in the sense that there may be no solution that is good for all cases, so having a few reasonable options may not be bad.

**Comment by timofeymukha** [comment]
Yeah, it's sort of like with statistics, hard to find a way that fits all corner cases.
