### ISSUE TITLE
output_dir does not work properly

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#863]
* Setting output_dir does not actually transfer the output to a directory of that name.
* Instead, it prepends all output files with the name. So there is like a forward-slash missing. 
* Adding / gives an error though, e.g. 
```
Fortran runtime error: Cannot open file 'outdir/bdry0.nek5000': No such file or directory
```

**Comment by njansson** [comment]
Probably something changed after we merged #720, which changed the output writing structure

**Comment by timofeymukha** [comment]
Just doing
`C%params%output_dir = trim(C%params%output_dir)//"/`
seems to work.

**Comment by njansson** [comment]
For which output is this causing an issue? the `fluid_output` is already trimming, but of course assumes that the users has provided a correct and valid path

**Comment by timofeymukha** [comment]
I mean, do we expect people to add the forward slash in the case file?

**Comment by njansson** [comment]
> I mean, do we expect people to add the forward slash in the case file?

True that is not too well designed
