### ISSUE TITLE
Sampler segfaults due to mod evaluation

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#872]
We have
```fortran
 else if (trim(write_control) .eq. 'nsamples') then
        this%freq_list(n) = ( write_par / this%T_end )
        this%T_list(n) = real(1d0,rp) / this%freq_list(n)
        this%tstep_interval_list(n) = 0
``` 
and then in the sampler_sample
```fortran
          else if ((samp%tstep_interval_list(i) .gt. 0) .and. &
               (mod(tstep,samp%tstep_interval_list(i)) .eq. 0)) then
``` 
The last line will segfault becase the tstep_interval_list is 0-valued.

Seems to only show up with O0 optimization, and this went unnoticed.

**Comment by timofeymukha** [comment]
I guess the idea is that only the first condition `(samp%tstep_interval_list(i) .gt. 0)` will be evaluated, but somehow the second one is as well.

**Comment by njansson** [comment]
> I guess the idea is that only the first condition `(samp%tstep_interval_list(i) .gt. 0)` will be evaluated, but somehow the second one is as well.

Fortran does not short circuit, thus all statements are always evaluated
