### ISSUE TITLE
JSON case file support in various compilers

### ISSUE THREAD

**Issue by njansson** [ExtremeFLOW/neko#891]
Test the new JSON case file ( #858 #831 ) with compilers not part of the usual workflow

- [x] Cray
- [x] NVIDIA
- [x] Intel
- [x] NEC
- [x] NAG
- [x] Fujitsu

**Comment by timofeymukha** [comment]
Did NVIDIA actually work?

**Comment by njansson** [comment]
> Did NVIDIA actually work?

Sorry, thought that you had tried it. Now removed ;)

**Comment by timofeymukha** [comment]
No, I guess NVIDIA is bound to fail, since it doesn't compile the json-fortran well, as we saw before.

**Comment by njansson** [comment]
> No, I guess NVIDIA is bound to fail, since it doesn't compile the json-fortran well, as we saw before.

That might be blocker, due to machines like Leonardo/Alps etc :(

**Comment by timofeymukha** [comment]
I mean, we were well aware of this and consciously decided to proceed on the 2023-05-05 meeting

**Comment by njansson** [comment]
Confirmed to work with NAG Fortran v7.1 + json-fortran v7.1.0

**Comment by njansson** [comment]
Confirmed to work with NEC Fortran v3.5.1 + patched json-fortran v7.1.0 (patch removed UC4 pragmas)

**Comment by timofeymukha** [comment]
Hoping for the best with Fujitsu for now.
