### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by njansson** [ExtremeFLOW/neko#947]
Write-up generic instruction on how to compile Neko and all dependencies (both required and optional).  The instructions should be part of the manual

- [x]  #992 
- [x]  #993 
- [x] #1025

**Comment by njansson** [comment]
The intent is to complete the effort started in 19c8415e0bda63bdf8fb23d3f4b134bda92a53da

**Comment by timfelle** [comment]
A suggestion could be to copy the content of the discussion pages into the documentation as well. Alternatively adding links to the relevant discussion pages could also be a way to do it.

- https://github.com/ExtremeFLOW/neko/discussions/665
- https://github.com/ExtremeFLOW/neko/discussions/601
- https://github.com/ExtremeFLOW/neko/discussions/539
- https://github.com/ExtremeFLOW/neko/discussions/585
- https://github.com/ExtremeFLOW/neko/discussions/496
- https://github.com/ExtremeFLOW/neko/discussions/540

**Comment by njansson** [comment]
> A suggestion could be to copy the content of the discussion pages into the documentation as well. Alternatively adding links to the relevant discussion pages could also be a way to do it.
> 
> * [Neko on LUMI-G #665](https://github.com/ExtremeFLOW/neko/discussions/665)
> * [Neko on Piz Daint #601](https://github.com/ExtremeFLOW/neko/discussions/601)
> * [Installation on Dardel #539](https://github.com/ExtremeFLOW/neko/discussions/539)
> * [Neko on AMD GPUs #585](https://github.com/ExtremeFLOW/neko/discussions/585)
> * [Basic installation under WSL/Ubuntu 20.04  with spack #496](https://github.com/ExtremeFLOW/neko/discussions/496)
> * [Neko on NVIDIA GPUs #540](https://github.com/ExtremeFLOW/neko/discussions/540)

Indeed, I had similar ideas, reusing the generic NVIDIA and AMD instructions for the manual, and the put links to more machine specific instructions.
