### ISSUE TITLE
Geometry subset selection

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#965]
We need to eventually add support for defining named subsets of geometry to be to localize the effects of sources or relevant simcomps. Like a localized heat source and that sort of stuff. One can think of what type of entities are relevant. An obvious one is a list of dofs, but perhaps a list of faces and a list of elements can also be relevant in some contexts. We may want to create a way for defining the entities from some primitive shapes, e.g. a box, a sphere, etc. Not sure if it is reasonable to do the selection always at runtime or if it should be done prior to the run with definitions saved to some file.

This is probably a more long-term project, given that there is more urgent stuff, but good to have in the list, so we can have it in the back of our heads.

**Comment by njansson** [comment]
Can't we use `zone_t` for the marking, or do we need more functionality for the markers (besides adding a name field in the zone type)?

**Comment by timofeymukha** [comment]
`zone_t` is currently for selecting faces only, right? So we need something for more or less arbitrary volumes as well.

**Comment by njansson** [comment]
> `zone_t` is currently for selecting faces only, right? So we need something for more or less arbitrary volumes as well.

Yes that's how it's used. But the design is to store tuples, currently `(facet, el)` but it can be arbitrary, and we can even extend it to hold arbitrary mapping

**Comment by timofeymukha** [comment]
yes, that is probably the right direction for the "backend".

**Comment by timfelle** [comment]
Since the geometry subsets PR is done is this issue done as well?

**Comment by njansson** [comment]
Indeed, isn't this kind of done now with the about mention PR merged?

**Comment by timofeymukha** [comment]
Yes, I think we can close!
