### ISSUE TITLE
Stress formulation

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#982]
A fresh issue for the stress formulation.

A small list with pointers from Nek5000:

* Different way of computing the viscous stress tensor in the pressure equation, crespsp.
* Small modification of a scaling parameter in the computation of the velocity residual in cresvsp or cresvsp_weak.
* In the velocity residual computaion, ophx calls axhmsf in subs1.f, which computes the coupled Helmholtz matrix-vector products.
* The coupled Helmholz solver hmhzsf called in ophinv
* Which in turn calls `cggosf` in `subs1`, which is the CG solver for the coupled helmholz.

Adding come concrete items to start with:

- [ ] coupled ax_helm subroutine.
- [ ] CG using the coupled ax_helm subroutine.
- [ ] GS using the coupled ax_helm subroutine.

**Comment by njansson** [comment]
Coupled ax, CG (with working GS) is implemented in https://github.com/ExtremeFLOW/neko/tree/feature/stress_formulation

But needs testing before we can merge.

**Comment by timofeymukha** [comment]
Stress formulation now in develop.
